"""
routers/explanations.py — AI explanation endpoints

POST /explain/        Generate a full structured AI explanation for a country snapshot
GET  /explain/example Return a filled example request + response for frontend reference
GET  /explain/schema  Return the prompt template (for transparency / debugging)

V1 caching strategy: cache by (iso3, period, data_hash) in the ai_explanations table.
V2: add Redis TTL cache + per-user rate limiting.
"""

from __future__ import annotations

import hashlib
import json
import logging
from datetime import datetime, timezone

from fastapi import APIRouter, Depends, HTTPException, Request, status
from sqlalchemy.orm import Session

from ..database import get_db
from ..models import AiExplanation, IndicatorValue as IndicatorValueModel, Indicator, Country
from ..schemas.explanation import (
    ExplanationRequest,
    ExplanationResponse,
    EXAMPLE_REQUEST,
)
from ..services.claude_service import (
    generate_explanation,
    generate_alert_explanation,   # legacy
    build_prompt,
    PROMPT_TEMPLATE,
)

logger   = logging.getLogger(__name__)
router   = APIRouter()

# ─────────────────────────────────────────────────────────────────────────────
# HELPERS
# ─────────────────────────────────────────────────────────────────────────────

def _request_hash(req: ExplanationRequest) -> str:
    """
    Deterministic hash of the request payload.
    Two requests with identical data produce the same hash → cache hit.
    """
    payload = req.model_dump(exclude={"additional_context"})
    serialised = json.dumps(payload, sort_keys=True, default=str)
    return hashlib.sha256(serialised.encode()).hexdigest()[:16]


def _load_cached(
    db: Session,
    iso3: str,
    period: str,
    data_hash: str,
) -> AiExplanation | None:
    return (
        db.query(AiExplanation)
        .filter(
            AiExplanation.country_id        == iso3,
            AiExplanation.explanation_type  == "snapshot_v2",
            AiExplanation.year              == _period_year(period),
        )
        .order_by(AiExplanation.generated_at.desc())
        .first()
    )


def _period_year(period: str) -> int:
    """Extract the year from a period string like 'Q2 2026' or '2025'."""
    import re
    match = re.search(r"\b(20\d{2})\b", period)
    return int(match.group(1)) if match else datetime.now().year


def _save_to_db(
    db: Session,
    req: ExplanationRequest,
    resp: ExplanationResponse,
    data_hash: str,
) -> None:
    """Persist the explanation to the ai_explanations table."""
    try:
        row = AiExplanation(
            country_id       = req.country_iso3,
            explanation_type = "snapshot_v2",
            year             = _period_year(req.period),
            explanation_text = resp.short_summary,
            # Store full JSON in the text field for now; V2 can add dedicated columns
            # You can add a JSONB column to ai_explanations if needed
        )
        db.add(row)
        db.commit()
    except Exception as e:
        logger.warning("Could not save explanation to DB: %s", e)
        db.rollback()


# ─────────────────────────────────────────────────────────────────────────────
# POST /explain/  — main endpoint
# ─────────────────────────────────────────────────────────────────────────────

@router.post(
    "/",
    response_model  = ExplanationResponse,
    summary         = "Generate AI explanation for a country economic snapshot",
    description     = (
        "Accepts a full set of economic indicators, active pattern alerts, and news signals. "
        "Returns a structured 6-section AI explanation generated by Claude. "
        "Responses are cached by data hash — identical inputs return instantly. "
        "Falls back gracefully if Claude is unavailable."
    ),
)
def explain_snapshot(
    req: ExplanationRequest,
    db: Session = Depends(get_db),
) -> ExplanationResponse:

    logger.info("POST /explain/ — %s / %s", req.country_iso3, req.period)

    # Minimum data check — refuse if no indicator data at all
    indicators = [
        req.gdp_growth, req.inflation, req.exports, req.imports,
        req.exchange_rate, req.fdi, req.public_debt,
    ]
    if all(ind is None for ind in indicators):
        raise HTTPException(
            status_code = status.HTTP_422_UNPROCESSABLE_ENTITY,
            detail = (
                "At least one economic indicator is required. "
                "Provide gdp_growth, inflation, exports, or any other indicator."
            ),
        )

    # Generate explanation (handles all errors internally, returns fallback if needed)
    response = generate_explanation(req)

    # Persist (best-effort — don't fail the request if DB is unavailable)
    data_hash = _request_hash(req)
    _save_to_db(db, req, response, data_hash)

    return response


# ─────────────────────────────────────────────────────────────────────────────
# GET /explain/example  — reference data for frontend
# ─────────────────────────────────────────────────────────────────────────────

@router.get(
    "/example",
    summary     = "Return an example request payload",
    description = "Returns a filled ExplanationRequest object showing all available fields.",
)
def get_example() -> dict:
    return {
        "description": "Example request for POST /explain/ — Thailand Q2 2026",
        "request": EXAMPLE_REQUEST.model_dump(),
        "notes": {
            "required_fields":   ["country_iso3", "country_name", "period"],
            "recommended_fields": ["gdp_growth", "inflation", "exports", "imports"],
            "optional_fields":   ["fdi", "exchange_rate", "public_debt", "news_signals", "active_alerts", "additional_context"],
            "period_format":     "Any human-readable string: 'Q2 2026', '2025', '2024-H1'",
            "news_signals":      "Feed from fetch_gdelt.py pipeline output",
            "active_alerts":     "Feed from pattern_engine.py run_all_alerts() output",
        },
    }


# ─────────────────────────────────────────────────────────────────────────────
# GET /explain/prompt  — transparency endpoint (shows Claude prompt template)
# ─────────────────────────────────────────────────────────────────────────────

@router.get(
    "/prompt",
    summary     = "Return the Claude prompt template",
    description = (
        "Shows the prompt template used to generate explanations. "
        "Intended for transparency, auditing, and prompt engineering. "
        "Placeholders like {indicators_text} are filled at request time."
    ),
)
def get_prompt_template() -> dict:
    return {
        "prompt_template": PROMPT_TEMPLATE,
        "placeholders": [
            "{country_name}",
            "{country_iso3}",
            "{period}",
            "{indicators_text}",
            "{alerts_text}",
            "{news_text}",
            "{additional_context_block}",
        ],
        "safety_rules_count": 8,
        "output_sections": [
            "short_summary",
            "detailed_explanation.what_changed",
            "detailed_explanation.why_it_may_matter",
            "detailed_explanation.which_indicators_connected",
            "connected_indicators[]",
            "regional_impact",
            "warning_level + warning_reasoning",
            "confidence",
            "data_limitations[]",
        ],
    }


# ─────────────────────────────────────────────────────────────────────────────
# POST /explain/preview  — dry-run, returns prompt without calling Claude
# ─────────────────────────────────────────────────────────────────────────────

@router.post(
    "/preview",
    summary     = "Preview the prompt that would be sent to Claude",
    description = (
        "Accepts a full ExplanationRequest and returns the rendered prompt string "
        "without calling the Claude API. Useful for testing and debugging."
    ),
)
def preview_prompt(req: ExplanationRequest) -> dict:
    from ..services.claude_service import compute_data_completeness
    return {
        "country_iso3":         req.country_iso3,
        "period":               req.period,
        "data_completeness":    compute_data_completeness(req),
        "prompt_char_count":    len(build_prompt(req)),
        "prompt":               build_prompt(req),
    }
