"use client";

/**
 * app/trade/page.tsx — Trade Relationships & Dependency Risk
 *
 * Shows bilateral trade data for 10 SEA countries against 7 key partners.
 *
 * Sections:
 *  1. Dependency Risk Heatmap  — 10 × 7 color-coded matrix
 *  2. Country Deep-dive        — select a country, see full partner breakdown
 *  3. Trade Balance Overview   — exports vs imports bar chart per country
 *  4. Top Bilateral Flows      — largest single trade relationships
 *
 * Data: pipeline/data/processed/trade_flows.json
 *       (generated by pipeline/fetch_comtrade.py)
 */

import { useState, useMemo } from "react";
import CompareBarChart from "@/components/charts/CompareBarChart";
import {
  TF_META, TF_REPORTERS, TF_PARTNERS, TF_DATA_STATUS, TF_LATEST_YEAR,
  DEPENDENCY_RISK_MATRIX,
  getCountryDependency, getPartnerRisk, getBilateralHistory, getTopPartner,
  RISK_BADGE_STYLE, RISK_DOT_COLOR, RISK_CELL_BG,
  type DependencyRisk, type TfCountry,
} from "@/data/trade-flows";
import { cn } from "@/lib/utils";

// ── Helpers ───────────────────────────────────────────────────────────────────

function fmtB(val: number | undefined | null): string {
  if (val == null) return "—";
  if (Math.abs(val) >= 1000) return `$${(val / 1000).toFixed(1)}T`;
  return `$${val.toFixed(1)}B`;
}

function RiskChip({ risk, compact = false }: { risk: DependencyRisk; compact?: boolean }) {
  const s = RISK_BADGE_STYLE[risk];
  return (
    <span className={cn(
      "inline-flex items-center gap-1 font-semibold rounded-full",
      compact ? "text-[9px] px-1.5 py-0.5" : "text-xs px-2 py-0.5",
      s.bg, s.text,
    )}>
      <span className={cn("w-1.5 h-1.5 rounded-full", RISK_DOT_COLOR[risk])} />
      {s.label}
    </span>
  );
}

// ── Main page ─────────────────────────────────────────────────────────────────

export default function TradePage() {
  const [selectedReporter, setSelectedReporter] = useState<string>("THA");
  const [selectedYear,     setSelectedYear]     = useState<number>(TF_LATEST_YEAR);
  const [activeTab,        setActiveTab]         = useState<"matrix" | "country" | "balance" | "flows">("matrix");

  const dep = getCountryDependency(selectedReporter, selectedYear);
  const reporterMeta = TF_REPORTERS.find(r => r.code === selectedReporter);

  // Trade balance bar chart data
  const balanceBarData = useMemo(() =>
    TF_REPORTERS.map(r => {
      const d = getCountryDependency(r.code, selectedYear);
      return {
        countryId:   r.code,
        countryName: r.name,
        flagEmoji:   r.flag,
        value:       d?.trade_balance_usd_b ?? 0,
        riskLevel:   (d?.trade_balance_usd_b ?? 0) < -5 ? "high" as const
                   : (d?.trade_balance_usd_b ?? 0) < 0  ? "medium" as const
                   : "low" as const,
      };
    })
  , [selectedYear]);

  // Top 10 bilateral flows by value
  const topFlows = useMemo(() => {
    const pairs: Array<{
      reporter: TfCountry;
      partner:  TfCountry;
      exports:  number;
      imports:  number;
      total:    number;
      risk:     DependencyRisk;
    }> = [];
    for (const rep of TF_REPORTERS) {
      for (const prt of TF_PARTNERS) {
        const risk = getPartnerRisk(rep.code, prt.code, selectedYear);
        if (!risk || risk.total_bilateral_usd_b === 0) continue;
        pairs.push({
          reporter: rep,
          partner:  prt,
          exports:  risk.exports_usd_b,
          imports:  risk.imports_usd_b,
          total:    risk.total_bilateral_usd_b,
          risk:     risk.dependency_risk,
        });
      }
    }
    return pairs.sort((a, b) => b.total - a.total).slice(0, 12);
  }, [selectedYear]);

  const years = TF_META.years ?? [TF_LATEST_YEAR];

  return (
    <div className="p-7 max-w-7xl mx-auto">

      {/* ── Header ────────────────────────────────────────────────────────── */}
      <div className="flex items-start justify-between mb-6">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 tracking-tight">
            Trade Relationships &amp; Dependency Risk
          </h1>
          <p className="text-slate-500 text-sm mt-0.5">
            10 SEA countries · 7 key partners ·{" "}
            {TF_DATA_STATUS === "live"
              ? <span className="text-emerald-600 font-medium">
                  {TF_META.source.split("/")[0].trim()}
                </span>
              : <span className="text-amber-600">sample data</span>
            }
          </p>
        </div>

        {/* Year selector + data note */}
        <div className="flex items-center gap-4">
          <div>
            <p className="text-[10px] font-semibold uppercase tracking-widest text-slate-400 mb-1">
              Reference Year
            </p>
            <div className="flex gap-1">
              {years.map(yr => (
                <button
                  key={yr}
                  onClick={() => setSelectedYear(yr)}
                  className={cn(
                    "text-xs px-2.5 py-1 rounded-lg border transition-colors",
                    selectedYear === yr
                      ? "bg-slate-800 text-white border-slate-800"
                      : "border-slate-200 text-slate-600 hover:bg-slate-50",
                  )}
                >
                  {yr}
                </button>
              ))}
            </div>
          </div>

          {TF_DATA_STATUS !== "live" && (
            <div className="text-xs bg-amber-50 border border-amber-200 rounded-lg px-3 py-2 text-amber-700 max-w-xs">
              Run{" "}
              <code className="font-mono bg-white/60 px-1 rounded">
                python pipeline/fetch_comtrade.py
              </code>
              {" "}to load live trade data
            </div>
          )}
        </div>
      </div>

      {/* ── Tab nav ───────────────────────────────────────────────────────── */}
      <div className="flex gap-1 mb-6 border-b border-slate-200">
        {([
          { key: "matrix",  label: "Dependency Matrix",   icon: "⊞" },
          { key: "country", label: "Country Deep-dive",   icon: "◎" },
          { key: "balance", label: "Trade Balance",        icon: "⇌" },
          { key: "flows",   label: "Top Bilateral Flows", icon: "↔" },
        ] as const).map(tab => (
          <button
            key={tab.key}
            onClick={() => setActiveTab(tab.key)}
            className={cn(
              "flex items-center gap-1.5 px-4 py-2.5 text-sm border-b-2 -mb-px transition-colors",
              activeTab === tab.key
                ? "border-indigo-600 text-indigo-700 font-semibold"
                : "border-transparent text-slate-500 hover:text-slate-700",
            )}
          >
            <span>{tab.icon}</span> {tab.label}
          </button>
        ))}
      </div>

      {/* ══════════════════════════════════════════════════════════════════════
          TAB 1 — DEPENDENCY RISK HEATMAP
      ══════════════════════════════════════════════════════════════════════ */}
      {activeTab === "matrix" && (
        <div className="card overflow-hidden">
          <div className="px-5 py-4 border-b border-slate-100 flex items-center justify-between">
            <div>
              <h2 className="font-semibold text-slate-900">Dependency Risk Matrix — {selectedYear}</h2>
              <p className="text-xs text-slate-400 mt-0.5">
                partner_share = bilateral_trade / total_trade · &gt;40% = High · 20–40% = Medium · &lt;20% = Low
              </p>
            </div>
            <div className="flex items-center gap-3 text-xs">
              {(["high","medium","low"] as DependencyRisk[]).map(r => (
                <span key={r} className="flex items-center gap-1">
                  <span className={cn("w-2.5 h-2.5 rounded-full", RISK_DOT_COLOR[r])} />
                  {RISK_BADGE_STYLE[r].label}
                </span>
              ))}
            </div>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="border-b border-slate-100 bg-slate-50/60">
                  <th className="px-5 py-3 text-left text-xs font-semibold text-slate-500 uppercase tracking-wide w-36">
                    SEA Reporter
                  </th>
                  {TF_PARTNERS.map(p => (
                    <th key={p.code}
                        className="px-3 py-3 text-center text-xs font-semibold text-slate-500 uppercase tracking-wide">
                      <div className="flex flex-col items-center gap-0.5">
                        <span>{p.flag}</span>
                        <span>{p.name.split(" ")[0]}</span>
                      </div>
                    </th>
                  ))}
                  <th className="px-5 py-3 text-right text-xs font-semibold text-slate-500 uppercase tracking-wide">
                    Exports
                  </th>
                  <th className="px-5 py-3 text-right text-xs font-semibold text-slate-500 uppercase tracking-wide">
                    Imports
                  </th>
                  <th className="px-5 py-3 text-right text-xs font-semibold text-slate-500 uppercase tracking-wide">
                    Balance
                  </th>
                </tr>
              </thead>
              <tbody>
                {TF_REPORTERS.map(rep => {
                  const dep      = getCountryDependency(rep.code, selectedYear);
                  const topExp   = getTopPartner(rep.code, "export", selectedYear);
                  const isActive = selectedReporter === rep.code;

                  return (
                    <tr
                      key={rep.code}
                      className={cn(
                        "border-b border-slate-50 cursor-pointer transition-colors",
                        isActive ? "bg-indigo-50/60" : "hover:bg-slate-50/40",
                      )}
                      onClick={() => { setSelectedReporter(rep.code); setActiveTab("country"); }}
                    >
                      <td className="px-5 py-3.5">
                        <div className="flex items-center gap-2">
                          <span className="text-xl shrink-0">{rep.flag}</span>
                          <div>
                            <p className="font-medium text-slate-900 text-sm">{rep.name}</p>
                            {topExp && (
                              <p className="text-[10px] text-slate-400">
                                top: {topExp.flag} {topExp.share_pct.toFixed(0)}% exp
                              </p>
                            )}
                          </div>
                        </div>
                      </td>

                      {/* Risk cells per partner */}
                      {TF_PARTNERS.map(prt => {
                        const risk     = DEPENDENCY_RISK_MATRIX[rep.code]?.[prt.code] ?? "low";
                        const partner  = dep?.by_partner?.[prt.code];
                        return (
                          <td key={prt.code} className="px-2 py-3 text-center">
                            <div className={cn(
                              "mx-auto rounded-lg border px-2 py-1.5 text-center min-w-[52px]",
                              RISK_CELL_BG[risk],
                            )}>
                              <p className={cn(
                                "text-[10px] font-bold uppercase tracking-wide",
                                risk === "high"   ? "text-red-700"
                                : risk === "medium" ? "text-amber-700"
                                : "text-emerald-700",
                              )}>
                                {risk === "high" ? "HIGH" : risk === "medium" ? "MED" : "low"}
                              </p>
                              {partner && (
                                <p className="text-[9px] text-slate-500 tabular-nums mt-0.5">
                                  {partner.partner_share_pct.toFixed(0)}%
                                </p>
                              )}
                            </div>
                          </td>
                        );
                      })}

                      <td className="px-5 py-3.5 text-right">
                        <span className="text-sm font-medium tabular-nums text-emerald-700">
                          {fmtB(dep?.total_exports_usd_b)}
                        </span>
                      </td>
                      <td className="px-5 py-3.5 text-right">
                        <span className="text-sm font-medium tabular-nums text-indigo-600">
                          {fmtB(dep?.total_imports_usd_b)}
                        </span>
                      </td>
                      <td className="px-5 py-3.5 text-right">
                        {dep && (
                          <span className={cn(
                            "text-sm font-semibold tabular-nums",
                            dep.trade_balance_usd_b >= 0 ? "text-emerald-600" : "text-red-500",
                          )}>
                            {dep.trade_balance_usd_b >= 0 ? "+" : ""}
                            {fmtB(dep.trade_balance_usd_b)}
                          </span>
                        )}
                      </td>
                    </tr>
                  );
                })}
              </tbody>
            </table>
          </div>

          <div className="px-5 py-3 bg-slate-50/50 border-t border-slate-100 text-[10px] text-slate-400">
            Click any row to see the full country breakdown · {TF_META.dependency_formula}
          </div>
        </div>
      )}

      {/* ══════════════════════════════════════════════════════════════════════
          TAB 2 — COUNTRY DEEP-DIVE
      ══════════════════════════════════════════════════════════════════════ */}
      {activeTab === "country" && (
        <div>
          {/* Country picker */}
          <div className="flex gap-2 mb-6 flex-wrap">
            {TF_REPORTERS.map(r => (
              <button
                key={r.code}
                onClick={() => setSelectedReporter(r.code)}
                className={cn(
                  "flex items-center gap-1.5 px-3 py-1.5 rounded-lg border text-xs font-medium transition-colors",
                  selectedReporter === r.code
                    ? "bg-slate-800 text-white border-slate-800"
                    : "border-slate-200 text-slate-600 bg-white hover:bg-slate-50",
                )}
              >
                <span>{r.flag}</span>
                <span>{r.name}</span>
              </button>
            ))}
          </div>

          {dep && reporterMeta ? (
            <>
              {/* Summary cards */}
              <div className="grid grid-cols-3 gap-4 mb-6">
                <div className="card-p border-t-4 border-t-emerald-500">
                  <p className="text-[10px] font-semibold uppercase tracking-wide text-slate-400 mb-1.5">Total Exports {selectedYear}</p>
                  <p className="text-2xl font-bold text-emerald-600 tabular-nums">{fmtB(dep.total_exports_usd_b)}</p>
                  <p className="text-xs text-slate-400 mt-1">Top: {getTfCountry(dep.top_export_partner)?.flag} {dep.top_export_share_pct.toFixed(1)}%</p>
                </div>
                <div className="card-p border-t-4 border-t-indigo-400">
                  <p className="text-[10px] font-semibold uppercase tracking-wide text-slate-400 mb-1.5">Total Imports {selectedYear}</p>
                  <p className="text-2xl font-bold text-indigo-600 tabular-nums">{fmtB(dep.total_imports_usd_b)}</p>
                  <p className="text-xs text-slate-400 mt-1">Top: {getTfCountry(dep.top_import_partner)?.flag} {dep.top_import_share_pct.toFixed(1)}%</p>
                </div>
                <div className={cn(
                  "card-p border-t-4",
                  dep.trade_balance_usd_b >= 0 ? "border-t-emerald-400" : "border-t-red-400",
                )}>
                  <p className="text-[10px] font-semibold uppercase tracking-wide text-slate-400 mb-1.5">Trade Balance {selectedYear}</p>
                  <p className={cn(
                    "text-2xl font-bold tabular-nums",
                    dep.trade_balance_usd_b >= 0 ? "text-emerald-600" : "text-red-500",
                  )}>
                    {dep.trade_balance_usd_b >= 0 ? "+" : ""}{fmtB(dep.trade_balance_usd_b)}
                  </p>
                  <p className="text-xs text-slate-400 mt-1">
                    {dep.trade_balance_usd_b >= 0 ? "Surplus" : "Deficit"} with tracked partners
                  </p>
                </div>
              </div>

              {/* Per-partner breakdown table */}
              <div className="card overflow-hidden mb-6">
                <div className="px-5 py-4 border-b border-slate-100">
                  <h3 className="font-semibold text-slate-900">
                    {reporterMeta.flag} {reporterMeta.name} — Partner Breakdown {selectedYear}
                  </h3>
                  <p className="text-xs text-slate-400 mt-0.5">
                    partner_share = bilateral_trade / total_trade
                  </p>
                </div>
                <table className="w-full text-sm">
                  <thead>
                    <tr className="border-b border-slate-100 bg-slate-50/60 text-xs text-slate-500 uppercase tracking-wide">
                      <th className="px-5 py-3 text-left">Partner</th>
                      <th className="px-5 py-3 text-right">Exports</th>
                      <th className="px-5 py-3 text-right">Imports</th>
                      <th className="px-5 py-3 text-right">Bilateral</th>
                      <th className="px-5 py-3 text-right">Trade Share</th>
                      <th className="px-5 py-3 text-center">Overall Risk</th>
                      <th className="px-5 py-3 text-center">Export Risk</th>
                      <th className="px-5 py-3 text-center">Import Risk</th>
                      <th className="px-5 py-3 text-right">Balance</th>
                    </tr>
                  </thead>
                  <tbody>
                    {TF_PARTNERS.map(prt => {
                      const bp = dep.by_partner[prt.code];
                      if (!bp) return null;
                      const balance = bp.exports_usd_b - bp.imports_usd_b;

                      /* Share bar width */
                      const barW = Math.min(100, bp.partner_share_pct * 2.5);

                      return (
                        <tr key={prt.code}
                            className="border-b border-slate-50 hover:bg-slate-50/60 transition-colors">
                          <td className="px-5 py-3.5">
                            <div className="flex items-center gap-2">
                              <span className="text-xl">{prt.flag}</span>
                              <div>
                                <p className="font-medium text-slate-900">{prt.name}</p>
                                {/* Mini share bar */}
                                <div className="w-24 h-1.5 bg-slate-100 rounded-full mt-1 overflow-hidden">
                                  <div
                                    className={cn(
                                      "h-full rounded-full",
                                      bp.dependency_risk === "high"   ? "bg-red-400"
                                      : bp.dependency_risk === "medium" ? "bg-amber-400"
                                      : "bg-emerald-400",
                                    )}
                                    style={{ width: `${barW}%` }}
                                  />
                                </div>
                              </div>
                            </div>
                          </td>
                          <td className="px-5 py-3.5 text-right font-medium text-emerald-700 tabular-nums">
                            {fmtB(bp.exports_usd_b)}
                            <p className="text-[10px] text-slate-400">{bp.export_share_pct.toFixed(1)}%</p>
                          </td>
                          <td className="px-5 py-3.5 text-right font-medium text-indigo-600 tabular-nums">
                            {fmtB(bp.imports_usd_b)}
                            <p className="text-[10px] text-slate-400">{bp.import_share_pct.toFixed(1)}%</p>
                          </td>
                          <td className="px-5 py-3.5 text-right font-semibold text-slate-900 tabular-nums">
                            {fmtB(bp.total_bilateral_usd_b)}
                          </td>
                          <td className="px-5 py-3.5 text-right">
                            <span className="font-bold tabular-nums text-slate-800">
                              {bp.partner_share_pct.toFixed(1)}%
                            </span>
                          </td>
                          <td className="px-5 py-3.5 text-center">
                            <RiskChip risk={bp.dependency_risk} />
                          </td>
                          <td className="px-5 py-3.5 text-center">
                            <RiskChip risk={bp.export_risk} compact />
                          </td>
                          <td className="px-5 py-3.5 text-center">
                            <RiskChip risk={bp.import_risk} compact />
                          </td>
                          <td className="px-5 py-3.5 text-right">
                            <span className={cn(
                              "font-medium tabular-nums",
                              balance >= 0 ? "text-emerald-600" : "text-red-500",
                            )}>
                              {balance >= 0 ? "+" : ""}{fmtB(balance)}
                            </span>
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>

              {/* 3-year bilateral trend for this country */}
              <div className="grid grid-cols-3 gap-4">
                {TF_PARTNERS.slice(0, 3).map(prt => {
                  const hist = getBilateralHistory(selectedReporter, prt.code);
                  const risk = DEPENDENCY_RISK_MATRIX[selectedReporter]?.[prt.code] ?? "low";
                  return (
                    <div key={prt.code} className="card-p">
                      <div className="flex items-center gap-2 mb-3">
                        <span className="text-lg">{prt.flag}</span>
                        <p className="text-xs font-semibold text-slate-700">{prt.name}</p>
                        <RiskChip risk={risk} compact />
                      </div>
                      <div className="space-y-1">
                        {hist.map(h => (
                          <div key={h.year} className="flex items-center gap-2 text-xs">
                            <span className="text-slate-400 w-9">{h.year}</span>
                            <div className="flex-1 flex gap-1 items-center">
                              <span className="text-emerald-600 w-14 text-right tabular-nums">
                                ↑{fmtB(h.exports_usd_b)}
                              </span>
                              <span className="text-indigo-600 w-14 text-right tabular-nums">
                                ↓{fmtB(h.imports_usd_b)}
                              </span>
                            </div>
                            <span className={cn(
                              "w-14 text-right tabular-nums font-medium",
                              h.balance >= 0 ? "text-emerald-600" : "text-red-500",
                            )}>
                              {h.balance >= 0 ? "+" : ""}{fmtB(h.balance)}
                            </span>
                          </div>
                        ))}
                      </div>
                    </div>
                  );
                })}
              </div>
            </>
          ) : (
            <div className="card-p text-center py-16">
              <p className="text-slate-400">No trade data for {selectedReporter} {selectedYear}</p>
            </div>
          )}
        </div>
      )}

      {/* ══════════════════════════════════════════════════════════════════════
          TAB 3 — TRADE BALANCE
      ══════════════════════════════════════════════════════════════════════ */}
      {activeTab === "balance" && (
        <div>
          <div className="card-p mb-6">
            <h2 className="font-semibold text-slate-900 mb-1">
              Trade Balance — 10 SEA Countries ({selectedYear})
            </h2>
            <p className="text-xs text-slate-400 mb-4">
              Exports (FOB) − Imports (CIF) · Positive = Surplus · Negative = Deficit
            </p>
            <CompareBarChart data={balanceBarData} unit="B" height={260} colorByRisk />
          </div>

          {/* Per-country summary grid */}
          <div className="grid grid-cols-2 gap-4">
            {TF_REPORTERS.map(rep => {
              const d = getCountryDependency(rep.code, selectedYear);
              if (!d) return null;
              const isSurplus = d.trade_balance_usd_b >= 0;
              return (
                <div key={rep.code}
                     className={cn(
                       "card-p border-l-4",
                       isSurplus ? "border-l-emerald-400" : "border-l-red-400",
                     )}>
                  <div className="flex items-start justify-between">
                    <div className="flex items-center gap-2">
                      <span className="text-2xl">{rep.flag}</span>
                      <div>
                        <p className="font-semibold text-slate-900">{rep.name}</p>
                        <p className={cn(
                          "text-sm font-bold tabular-nums",
                          isSurplus ? "text-emerald-600" : "text-red-500",
                        )}>
                          {isSurplus ? "Surplus " : "Deficit "}
                          {fmtB(Math.abs(d.trade_balance_usd_b))}
                        </p>
                      </div>
                    </div>
                    <div className="text-right text-xs text-slate-400">
                      <p>↑ Exp: <span className="text-emerald-600 font-medium">{fmtB(d.total_exports_usd_b)}</span></p>
                      <p>↓ Imp: <span className="text-indigo-600 font-medium">{fmtB(d.total_imports_usd_b)}</span></p>
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* ══════════════════════════════════════════════════════════════════════
          TAB 4 — TOP BILATERAL FLOWS
      ══════════════════════════════════════════════════════════════════════ */}
      {activeTab === "flows" && (
        <div>
          <p className="text-xs text-slate-400 mb-4">
            Top 12 bilateral trade relationships by total bilateral value (exports + imports) · {selectedYear}
          </p>
          <div className="grid grid-cols-2 gap-4">
            {topFlows.map((flow, i) => (
              <div key={`${flow.reporter.code}-${flow.partner.code}`}
                   className="card-p flex items-start gap-3">
                <span className="text-slate-400 text-sm font-bold w-5 shrink-0 mt-0.5">
                  {i + 1}
                </span>
                <div className="flex-1">
                  <div className="flex items-center gap-2 mb-1">
                    <span className="text-lg">{flow.reporter.flag}</span>
                    <span className="font-semibold text-slate-800 text-sm">{flow.reporter.name}</span>
                    <span className="text-slate-400">↔</span>
                    <span className="text-lg">{flow.partner.flag}</span>
                    <span className="font-semibold text-slate-800 text-sm">{flow.partner.name}</span>
                    <RiskChip risk={flow.risk} compact />
                  </div>
                  <div className="flex items-center gap-4 text-xs">
                    <span className="text-emerald-600 font-medium tabular-nums">
                      ↑ {fmtB(flow.exports)} exp
                    </span>
                    <span className="text-indigo-600 font-medium tabular-nums">
                      ↓ {fmtB(flow.imports)} imp
                    </span>
                    <span className="font-bold text-slate-900 tabular-nums ml-auto">
                      {fmtB(flow.total)} total
                    </span>
                  </div>
                  {/* Mini bar showing export vs import split */}
                  <div className="mt-2 h-1.5 bg-slate-100 rounded-full overflow-hidden flex">
                    <div
                      className="h-full bg-emerald-400 rounded-l-full"
                      style={{ width: `${(flow.exports / flow.total) * 100}%` }}
                    />
                    <div
                      className="h-full bg-indigo-400 rounded-r-full"
                      style={{ width: `${(flow.imports / flow.total) * 100}%` }}
                    />
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* ── Limitations footer ───────────────────────────────────────────── */}
      <div className="mt-8 card-p bg-slate-50/50 text-xs text-slate-400 space-y-1">
        <p className="font-semibold text-slate-500 text-[10px] uppercase tracking-wide mb-2">
          Data Limitations
        </p>
        {TF_META.limitations?.slice(0, 4).map((l, i) => (
          <p key={i}>• {l}</p>
        ))}
        <p className="mt-2 text-slate-500">
          Source: {TF_META.source} · Last updated: {TF_META.generated_at?.slice(0, 10)}
        </p>
      </div>
    </div>
  );
}

// ── Helper to get country meta by code (for display) ─────────────────────────
function getTfCountry(code: string) {
  return [...TF_REPORTERS, ...TF_PARTNERS, { code:"WLD", name:"World", flag:"🌐" }]
    .find(c => c.code === code);
}
