/**
 * frontend/data/news-signals.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * TypeScript adapter for GDELT real-time news signals.
 *
 * SOURCE FILE (generated by pipeline/fetch_gdelt_news.py):
 *   pipeline/data/processed/news_signals.json
 *
 * HOW TO REFRESH:
 *   cd pipeline
 *   python fetch_gdelt_news.py           # last 7 days, uses daily cache
 *   python fetch_gdelt_news.py --refresh # bypass cache, re-fetch all
 *   python fetch_gdelt_news.py --days 14 # extend look-back window
 *
 * EXPORTS
 * ───────
 *   NS_META              — metadata (generated_at, date range, status)
 *   NS_ARTICLES          — all enriched article records
 *   NS_DATA_STATUS       — "live" | "placeholder"
 *   NS_SOURCE_TRACKING   — {iso3 → {articles, sources, top_domain}}
 *   NS_CATEGORY_COUNTS   — {iso3 → {category → count}}
 *   NS_NEWS_COUNTS       — {iso3 → {political_risk_count, trade_news_count}}
 *
 *   toNewsEvent()        — convert one NsArticle → NewsEvent (for news page)
 *   NS_AS_NEWS_EVENTS    — precomputed NewsEvent[] (ready to use in pages)
 *
 *   POLITICAL_RISK_COUNTS — {iso3 → count} for the Pattern Alert Centre
 *   TRADE_NEWS_COUNTS     — {iso3 → count} for the Pattern Alert Centre
 *
 * CATEGORIES (13 total)
 * ──────────────────────
 *   tariff · conflict · disaster · border · protest · election
 *   policy · trade · technology · infrastructure · economy · politics
 * ─────────────────────────────────────────────────────────────────────────────
 */

// eslint-disable-next-line @typescript-eslint/no-require-imports
const _raw = require("../../pipeline/data/processed/news_signals.json") as NsJson;

import type { NewsEvent } from "@/data/sample-data";
import { ALL_COUNTRIES }   from "@/data/countries";


// ── Types ─────────────────────────────────────────────────────────────────────

export interface NsMeta {
  generated_at:       string;
  source:             string;
  api_url:            string;
  days_back:          number;
  start_date:         string;
  end_date:           string;
  total_articles:     number;
  unique_articles:    number;
  duplicates_removed: number;
  countries_fetched:  number;
  categories:         number;
  data_status:        string;
  refresh_note:       string;
}

export interface NsArticle {
  id:                   number;
  title:                string;
  url:                  string;
  source_domain:        string;
  date:                 string;   // "YYYY-MM-DD"
  country_code:         string;   // ISO3
  country_name:         string;
  category:             NsCategory;
  all_categories:       NsCategory[];
  tone:                 number;   // -1.0 to +1.0 (computed from title keywords)
  language:             string;
  impact_score:         number;   // 1–5
  connected_indicators: string[];
  source:               "gdelt";
  gdelt_seendate:       string;
  url_hash:             string;
}

export type NsCategory =
  | "tariff" | "conflict" | "disaster" | "border" | "protest" | "election"
  | "policy" | "trade" | "technology" | "infrastructure" | "economy" | "politics";

export interface NsSourceInfo {
  articles:   number;
  sources:    string[];
  top_domain: string;
}

export interface NsNewsCount {
  political_risk_count: number;
  trade_news_count:     number;
  total_articles:       number;
}

interface NsJson {
  meta:             NsMeta;
  source_tracking:  Record<string, NsSourceInfo>;
  category_counts:  Record<string, Record<string, number>>;
  news_counts:      Record<string, NsNewsCount>;
  articles:         NsArticle[];
}


// ── Core exports ──────────────────────────────────────────────────────────────

export const NS_META:             NsMeta                              = _raw.meta;
export const NS_ARTICLES:         NsArticle[]                        = _raw.articles;
export const NS_SOURCE_TRACKING:  Record<string, NsSourceInfo>       = _raw.source_tracking;
export const NS_CATEGORY_COUNTS:  Record<string, Record<string, number>> = _raw.category_counts;
export const NS_NEWS_COUNTS:      Record<string, NsNewsCount>        = _raw.news_counts;

/** "live" after fetch_gdelt_news.py runs; "placeholder" before */
export const NS_DATA_STATUS: "live" | "placeholder" =
  _raw.meta.data_status === "live" ? "live" : "placeholder";

/** Formatted last-fetch string for UI display */
export function fmtNsGeneratedAt(): string {
  const ts = NS_META.generated_at;
  if (!ts || ts === "placeholder") return "";
  try {
    return new Date(ts).toLocaleString("en-GB", {
      day: "2-digit", month: "short", hour: "2-digit", minute: "2-digit",
    });
  } catch {
    return ts;
  }
}


// ── Country flag / name lookup (covers all 17 countries) ─────────────────────
const _countryMeta = new Map(
  ALL_COUNTRIES.map(c => [c.iso3, { flag: c.flagEmoji, name: c.shortName }])
);

function getFlag(iso3: string): string {
  return _countryMeta.get(iso3)?.flag ?? "🌐";
}
function getShortName(iso3: string): string {
  return _countryMeta.get(iso3)?.name ?? iso3;
}


// ── Convert NsArticle → NewsEvent ─────────────────────────────────────────────

/**
 * Map NsArticle to the NewsEvent shape used by the news page and news cards.
 * ID offset = 5000 to avoid collisions with sample (1–999) and old GDELT (1000+).
 */
export function toNewsEvent(art: NsArticle): NewsEvent {
  const tone = art.tone ?? 0;

  const sentiment: NewsEvent["sentiment"] =
    tone > 0.1 ? "positive" : tone < -0.1 ? "negative" : "neutral";

  // Map NsCategory to NewsEvent category (extend type for new categories)
  const category = art.category as NewsEvent["category"];

  return {
    id:                 art.id + 5000,
    countryId:          art.country_code,
    headline:           art.title,
    summary:            art.title,                // GDELT provides title only
    category,
    sentiment,
    sentimentScore:     tone,
    publishedAt:        art.date,
    sourceName:         art.source_domain,
    impactLevel:        art.impact_score,
    impactedIndicators: art.connected_indicators,
    gdeltUrl:           art.url,
    gdeltTone:          tone,
    source:             "gdelt",
  };
}

/** All GDELT news signals pre-converted to NewsEvent shape */
export const NS_AS_NEWS_EVENTS: NewsEvent[] = NS_ARTICLES.map(toNewsEvent);


// ── Pattern Alert Centre helpers ──────────────────────────────────────────────

/**
 * Real GDELT-based political risk article count per country (last N days).
 * Counts articles in: politics, protest, conflict, election, border.
 *
 * Use these to update the "Political Risk News" indicator in the alerts page.
 * Returns 0 for countries not in the GDELT data.
 */
export const POLITICAL_RISK_COUNTS: Record<string, number> = Object.fromEntries(
  Object.entries(NS_NEWS_COUNTS).map(([iso3, c]) => [iso3, c.political_risk_count]),
);

/**
 * Real GDELT-based trade news article count per country (last N days).
 * Counts articles in: trade, tariff.
 *
 * Use these to update the "Trade News Count" indicator in the alerts page.
 */
export const TRADE_NEWS_COUNTS: Record<string, number> = Object.fromEntries(
  Object.entries(NS_NEWS_COUNTS).map(([iso3, c]) => [iso3, c.trade_news_count]),
);

/**
 * Countries with political risk news count above threshold (articles/week).
 * Used to generate live alert signals in the Pattern Alert Centre.
 */
export function getHighRiskCountries(threshold = 10): string[] {
  return Object.entries(POLITICAL_RISK_COUNTS)
    .filter(([, count]) => count >= threshold)
    .sort(([, a], [, b]) => b - a)
    .map(([iso3]) => iso3);
}

/**
 * Countries with high trade tension signals (above threshold articles/week).
 */
export function getHighTradeCountries(threshold = 5): string[] {
  return Object.entries(TRADE_NEWS_COUNTS)
    .filter(([, count]) => count >= threshold)
    .sort(([, a], [, b]) => b - a)
    .map(([iso3]) => iso3);
}

/**
 * Impact-5 articles from the last N days — the most critical signals.
 */
export const CRITICAL_SIGNALS: NsArticle[] = NS_ARTICLES.filter(
  a => a.impact_score >= 4,
).sort((a, b) => b.impact_score - a.impact_score);


// ── Category display metadata ─────────────────────────────────────────────────

export const NS_CATEGORY_META: Record<
  NsCategory,
  { label: string; icon: string; color: string }
> = {
  tariff:         { label: "Tariff",         icon: "📦", color: "bg-red-100 text-red-700"        },
  conflict:       { label: "Conflict",       icon: "⚔️", color: "bg-red-100 text-red-800"        },
  disaster:       { label: "Disaster",       icon: "🌊", color: "bg-orange-100 text-orange-700"  },
  border:         { label: "Border",         icon: "🚧", color: "bg-rose-100 text-rose-700"      },
  protest:        { label: "Protest",        icon: "✊", color: "bg-fuchsia-100 text-fuchsia-700"},
  election:       { label: "Election",       icon: "🗳️", color: "bg-violet-100 text-violet-700"  },
  policy:         { label: "Policy",         icon: "⚖️", color: "bg-indigo-100 text-indigo-700"  },
  trade:          { label: "Trade",          icon: "🤝", color: "bg-yellow-100 text-yellow-700"  },
  technology:     { label: "Technology",     icon: "💡", color: "bg-cyan-100 text-cyan-700"      },
  infrastructure: { label: "Infrastructure", icon: "🏗", color: "bg-teal-100 text-teal-700"      },
  economy:        { label: "Economy",        icon: "📈", color: "bg-blue-100 text-blue-700"      },
  politics:       { label: "Politics",       icon: "🏛", color: "bg-purple-100 text-purple-700"  },
};

/** All categories in priority order (most specific first) */
export const NS_CATEGORY_ORDER: NsCategory[] = [
  "tariff", "conflict", "disaster", "border", "protest", "election",
  "policy", "trade", "technology", "infrastructure", "economy", "politics",
];

export { getFlag, getShortName };
