/**
 * frontend/data/trade-flows.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * TypeScript adapter for bilateral trade data.
 *
 * SOURCE FILE (generated by pipeline/fetch_comtrade.py):
 *   pipeline/data/processed/trade_flows.json
 *
 * HOW TO REFRESH:
 *   cd pipeline
 *   python fetch_comtrade.py                    # free, no key needed
 *   python fetch_comtrade.py --refresh          # bypass cache
 *   # For UN Comtrade Plus API: add COMTRADE_SUBSCRIPTION_KEY to .env
 *
 * EXPORTS
 * ───────
 *   TF_META, TF_FLOWS, TF_DEPENDENCY, TF_SUMMARY, TF_DATA_STATUS
 *
 *   getCountryDependency(iso3, year)  → dependency data for one country-year
 *   getPartnerRisk(iso3, partner, year)  → risk level for one pair
 *   getAllDependencyRisks(year)   → matrix: {iso3 → {partner → risk}}
 *   getTopPartner(iso3, flow, year) → {code, name, share_pct}
 *   getTradeBalance(iso3, year)   → {exports, imports, balance}
 *
 *   DEPENDENCY_RISK_MATRIX  — precomputed {iso3 → {partner → WbDataQuality-like level}}
 *   TF_REPORTERS / TF_PARTNERS — country arrays
 *
 * DEPENDENCY RISK FORMULA
 * ─────────────────────────
 *   partner_share = (exports_to + imports_from) / (total_exports + total_imports)
 *   >40%   → "high"
 *   20-40% → "medium"
 *   <20%   → "low"
 * ─────────────────────────────────────────────────────────────────────────────
 */

// eslint-disable-next-line @typescript-eslint/no-require-imports
const _raw = require("../../pipeline/data/processed/trade_flows.json") as TfJson;
import { COMTRADE_SOURCE_BASE, type SourceMeta } from "@/lib/source-meta";


// ── Types ─────────────────────────────────────────────────────────────────────

export type DependencyRisk = "high" | "medium" | "low";

export interface TfMeta {
  generated_at:       string;
  source:             string;
  api_mode:           string;
  reporters:          number;
  partners:           number;
  years:              number[];
  has_monthly:        boolean;
  data_status:        string;
  limitations:        string[];
  dependency_formula: string;
  refresh_note:       string;
}

export interface TfFlow {
  reporter_code:      string;
  reporter_name:      string;
  partner_code:       string;
  partner_name:       string;
  year:               number;
  month:              number | null;
  period_label:       string;
  flow_code:          "X" | "M";
  flow_label:         "Export" | "Import";
  value_usd_b:        number;
  share_of_world_pct: number | null;
  source:             string;
  source_url:         string;
  last_updated:       string;
}

export interface TfPartnerRisk {
  exports_usd_b:         number;
  imports_usd_b:         number;
  total_bilateral_usd_b: number;
  partner_share:         number;
  partner_share_pct:     number;
  export_share:          number;
  export_share_pct:      number;
  import_share:          number;
  import_share_pct:      number;
  dependency_risk:       DependencyRisk;
  export_risk:           DependencyRisk;
  import_risk:           DependencyRisk;
}

export interface TfYearDependency {
  total_exports_usd_b:   number;
  total_imports_usd_b:   number;
  trade_balance_usd_b:   number;
  top_export_partner:    string;
  top_export_share_pct:  number;
  top_import_partner:    string;
  top_import_share_pct:  number;
  by_partner:            Record<string, TfPartnerRisk>;
}

export interface TfSummaryRow {
  reporter_code:            string;
  reporter_name:            string;
  year:                     number;
  total_exports_usd_b:      number;
  total_imports_usd_b:      number;
  trade_balance_usd_b:      number;
  top_export_partner:       string;
  top_export_share_pct:     number;
  top_import_partner:       string;
  top_import_share_pct:     number;
  china_export_risk:        DependencyRisk | null;
  china_import_risk:        DependencyRisk | null;
  china_overall_risk:       DependencyRisk | null;
  china_partner_share_pct:  number | null;
}

interface TfJson {
  meta:       TfMeta;
  flows:      TfFlow[];
  dependency: Record<string, Record<string, TfYearDependency>>;
  monthly:    TfFlow[];
  summary:    TfSummaryRow[];
}

// ── Core exports ──────────────────────────────────────────────────────────────

export const TF_META:       TfMeta                                        = _raw.meta;
export const TF_FLOWS:      TfFlow[]                                      = _raw.flows;
export const TF_DEPENDENCY: Record<string, Record<string, TfYearDependency>> = _raw.dependency;
export const TF_SUMMARY:    TfSummaryRow[]                                = _raw.summary;
export const TF_MONTHLY:    TfFlow[]                                      = _raw.monthly ?? [];

export const TF_DATA_STATUS: "live" | "placeholder" =
  _raw.meta.data_status === "live" ? "live" : "placeholder";

export const TF_LATEST_YEAR: number = Math.max(...(_raw.meta.years ?? [2023]));

// ── Source metadata ───────────────────────────────────────────────────────────

/**
 * Global Comtrade source metadata — applies to all trade flow records.
 */
export const TF_SOURCE_META: SourceMeta = {
  ...COMTRADE_SOURCE_BASE,
  fetched_at: _raw.meta.generated_at,
};

/**
 * Per-flow source metadata — uses the flow record's own source_url and last_updated.
 */
export function getFlowSourceMeta(flow: TfFlow): SourceMeta {
  return {
    ...COMTRADE_SOURCE_BASE,
    fetched_at:  flow.last_updated ?? _raw.meta.generated_at,
    source_url:  flow.source_url   ?? COMTRADE_SOURCE_BASE.source_url,
    source:      flow.source === "comtrade_wto_stats"
      ? "UN Comtrade / WTO Statistics"
      : flow.source ?? COMTRADE_SOURCE_BASE.source,
  };
}


// ── Reporter / Partner registry ───────────────────────────────────────────────

export interface TfCountry {
  code:  string;
  name:  string;
  flag:  string;
}

export const TF_REPORTERS: TfCountry[] = [
  { code: "THA", name: "Thailand",    flag: "🇹🇭" },
  { code: "VNM", name: "Vietnam",     flag: "🇻🇳" },
  { code: "MMR", name: "Myanmar",     flag: "🇲🇲" },
  { code: "KHM", name: "Cambodia",    flag: "🇰🇭" },
  { code: "LAO", name: "Laos",        flag: "🇱🇦" },
  { code: "MYS", name: "Malaysia",    flag: "🇲🇾" },
  { code: "SGP", name: "Singapore",   flag: "🇸🇬" },
  { code: "IDN", name: "Indonesia",   flag: "🇮🇩" },
  { code: "PHL", name: "Philippines", flag: "🇵🇭" },
  { code: "BRN", name: "Brunei",      flag: "🇧🇳" },
];

export const TF_PARTNERS: TfCountry[] = [
  { code: "CHN", name: "China",          flag: "🇨🇳" },
  { code: "USA", name: "United States",  flag: "🇺🇸" },
  { code: "JPN", name: "Japan",          flag: "🇯🇵" },
  { code: "IND", name: "India",          flag: "🇮🇳" },
  { code: "KOR", name: "South Korea",    flag: "🇰🇷" },
  { code: "AUS", name: "Australia",      flag: "🇦🇺" },
  { code: "EUU", name: "European Union", flag: "🇪🇺" },
];

// Combined lookup
const _allCountries = [...TF_REPORTERS, ...TF_PARTNERS, { code:"WLD", name:"World (Total)", flag:"🌐" }];
export function getTfCountry(code: string): TfCountry | undefined {
  return _allCountries.find(c => c.code === code);
}


// ── Lookup helpers ────────────────────────────────────────────────────────────

/** Get dependency data for one reporter country in a given year. */
export function getCountryDependency(
  iso3: string,
  year: number = TF_LATEST_YEAR,
): TfYearDependency | null {
  return TF_DEPENDENCY[iso3]?.[String(year)] ?? null;
}

/** Get the risk profile for one bilateral pair. */
export function getPartnerRisk(
  reporterIso3: string,
  partnerIso3:  string,
  year:         number = TF_LATEST_YEAR,
): TfPartnerRisk | null {
  return TF_DEPENDENCY[reporterIso3]?.[String(year)]?.by_partner?.[partnerIso3] ?? null;
}

/** Get dependency risk level for one bilateral pair. */
export function getDependencyRisk(
  reporterIso3: string,
  partnerIso3:  string,
  year:         number = TF_LATEST_YEAR,
): DependencyRisk {
  return getPartnerRisk(reporterIso3, partnerIso3, year)?.dependency_risk ?? "low";
}

/** Get the full dependency risk matrix for all reporters × partners in a year.  */
export function getAllDependencyRisks(year = TF_LATEST_YEAR): Record<string, Record<string, DependencyRisk>> {
  const result: Record<string, Record<string, DependencyRisk>> = {};
  for (const reporter of TF_REPORTERS) {
    result[reporter.code] = {};
    for (const partner of TF_PARTNERS) {
      result[reporter.code][partner.code] = getDependencyRisk(reporter.code, partner.code, year);
    }
  }
  return result;
}

/** Get the top trading partner for a reporter (by flow direction). */
export function getTopPartner(
  iso3:       string,
  flow:       "export" | "import" | "overall",
  year:       number = TF_LATEST_YEAR,
): { code: string; name: string; flag: string; share_pct: number } | null {
  const dep = getCountryDependency(iso3, year);
  if (!dep) return null;

  const code = flow === "export" ? dep.top_export_partner
             : flow === "import" ? dep.top_import_partner
             : dep.top_export_partner;  // overall: use export partner
  const share_pct = flow === "export" ? dep.top_export_share_pct
                  : dep.top_import_share_pct;

  const country = getTfCountry(code);
  return {
    code,
    name:      country?.name ?? code,
    flag:      country?.flag ?? "🌐",
    share_pct,
  };
}

/** Get exports, imports, and trade balance for a country-year. */
export function getTradeBalance(
  iso3: string,
  year: number = TF_LATEST_YEAR,
): { exports: number; imports: number; balance: number } | null {
  const dep = getCountryDependency(iso3, year);
  if (!dep) return null;
  return {
    exports: dep.total_exports_usd_b,
    imports: dep.total_imports_usd_b,
    balance: dep.trade_balance_usd_b,
  };
}

/** Get bilateral export/import data from reporter to/from specific partner over years. */
export function getBilateralHistory(
  reporterIso3: string,
  partnerIso3:  string,
): Array<{ year: number; exports_usd_b: number; imports_usd_b: number; balance: number }> {
  const years = TF_META.years ?? [];
  return years.map(yr => {
    const risk = getPartnerRisk(reporterIso3, partnerIso3, yr);
    return {
      year:          yr,
      exports_usd_b: risk?.exports_usd_b ?? 0,
      imports_usd_b: risk?.imports_usd_b ?? 0,
      balance:       (risk?.exports_usd_b ?? 0) - (risk?.imports_usd_b ?? 0),
    };
  });
}


// ── Precomputed matrix ────────────────────────────────────────────────────────

/** Full dependency risk matrix for latest year: { reporter → { partner → risk } } */
export const DEPENDENCY_RISK_MATRIX = getAllDependencyRisks(TF_LATEST_YEAR);


// ── Display helpers ───────────────────────────────────────────────────────────

export const RISK_BADGE_STYLE: Record<DependencyRisk, { bg: string; text: string; label: string }> = {
  high:   { bg: "bg-red-100",    text: "text-red-700",    label: "High"   },
  medium: { bg: "bg-amber-100",  text: "text-amber-700",  label: "Medium" },
  low:    { bg: "bg-emerald-100",text: "text-emerald-700",label: "Low"    },
};

export const RISK_DOT_COLOR: Record<DependencyRisk, string> = {
  high:   "bg-red-500",
  medium: "bg-amber-400",
  low:    "bg-emerald-500",
};

export const RISK_CELL_BG: Record<DependencyRisk, string> = {
  high:   "bg-red-50 border-red-200",
  medium: "bg-amber-50 border-amber-200",
  low:    "bg-emerald-50 border-emerald-200",
};
