/**
 * frontend/data/trade-flows.ts
 * ─────────────────────────────────────────────────────────────────────────────
 * TypeScript adapter for bilateral trade data.
 *
 * SOURCE FILE (generated by scripts/fetch_un_comtrade.py):
 *   pipeline/data/processed/trade_flows.json
 *
 * Handles TWO JSON formats:
 *   ① Old format — has top-level keys: meta, flows, dependency, summary
 *   ② New pipeline format — has: source, records[], years[], reporters[]
 *      (normalised into the same shape at module load time)
 *
 * Safe for static builds: every property access uses ?. / ?? fallbacks so
 * prerendering never crashes even if the JSON is absent or partially formed.
 *
 * HOW TO REFRESH:
 *   python scripts/fetch_un_comtrade.py --all-years
 * ─────────────────────────────────────────────────────────────────────────────
 */

// eslint-disable-next-line @typescript-eslint/no-require-imports
const _rawFile = (() => {
  try {
    return require("../../pipeline/data/processed/trade_flows.json") as Record<string, unknown>;
  } catch {
    return {} as Record<string, unknown>;
  }
})();

import { COMTRADE_SOURCE_BASE, type SourceMeta } from "@/lib/source-meta";


// ── Types ─────────────────────────────────────────────────────────────────────

export type DependencyRisk = "high" | "medium" | "low";

export interface TfMeta {
  generated_at:       string;
  source:             string;
  api_mode:           string;
  reporters:          number;
  partners:           number;
  years:              number[];
  has_monthly:        boolean;
  data_status:        string;
  limitations:        string[];
  dependency_formula: string;
  refresh_note:       string;
}

export interface TfFlow {
  reporter_code:      string;
  reporter_name:      string;
  partner_code:       string;
  partner_name:       string;
  year:               number;
  month:              number | null;
  period_label:       string;
  flow_code:          "X" | "M";
  flow_label:         "Export" | "Import";
  value_usd_b:        number;
  share_of_world_pct: number | null;
  source:             string;
  source_url:         string;
  last_updated:       string;
}

export interface TfPartnerRisk {
  exports_usd_b:         number;
  imports_usd_b:         number;
  total_bilateral_usd_b: number;
  partner_share:         number;
  partner_share_pct:     number;
  export_share:          number;
  export_share_pct:      number;
  import_share:          number;
  import_share_pct:      number;
  dependency_risk:       DependencyRisk;
  export_risk:           DependencyRisk;
  import_risk:           DependencyRisk;
}

export interface TfYearDependency {
  total_exports_usd_b:   number;
  total_imports_usd_b:   number;
  trade_balance_usd_b:   number;
  top_export_partner:    string;
  top_export_share_pct:  number;
  top_import_partner:    string;
  top_import_share_pct:  number;
  by_partner:            Record<string, TfPartnerRisk>;
}

export interface TfSummaryRow {
  reporter_code:            string;
  reporter_name:            string;
  year:                     number;
  total_exports_usd_b:      number;
  total_imports_usd_b:      number;
  trade_balance_usd_b:      number;
  top_export_partner:       string;
  top_export_share_pct:     number;
  top_import_partner:       string;
  top_import_share_pct:     number;
  china_export_risk:        DependencyRisk | null;
  china_import_risk:        DependencyRisk | null;
  china_overall_risk:       DependencyRisk | null;
  china_partner_share_pct:  number | null;
}

interface TfJson {
  meta:       TfMeta;
  flows:      TfFlow[];
  dependency: Record<string, Record<string, TfYearDependency>>;
  monthly:    TfFlow[];
  summary:    TfSummaryRow[];
}


// ── Normalisation: flat-records → TfJson ─────────────────────────────────────

function _emptyPartnerRisk(): TfPartnerRisk {
  return {
    exports_usd_b: 0, imports_usd_b: 0, total_bilateral_usd_b: 0,
    partner_share: 0, partner_share_pct: 0,
    export_share:  0, export_share_pct:  0,
    import_share:  0, import_share_pct:  0,
    dependency_risk: "low", export_risk: "low", import_risk: "low",
  };
}

function _riskLevel(pct: number): DependencyRisk {
  return pct >= 40 ? "high" : pct >= 20 ? "medium" : "low";
}

/** Build dependency structure from flat pipeline records[]. */
function _buildDependency(
  records: Array<Record<string, unknown>>,
): Record<string, Record<string, TfYearDependency>> {
  const dep: Record<string, Record<string, TfYearDependency>> = {};

  // ── Pass 1: populate raw values ────────────────────────────────────────────
  for (const rec of records) {
    const country = rec["country_code"] as string | undefined;
    const year    = String(rec["year"] ?? "");
    const code    = (rec["indicator_code"] as string | undefined) ?? "";
    const val     = rec["value"] != null ? Number(rec["value"]) : null;

    if (!country || !year || year === "undefined") continue;

    dep[country]        ??= {};
    dep[country][year]  ??= {
      total_exports_usd_b: 0, total_imports_usd_b: 0, trade_balance_usd_b: 0,
      top_export_partner: "", top_export_share_pct: 0,
      top_import_partner: "", top_import_share_pct: 0,
      by_partner: {},
    };
    const d = dep[country][year];

    if (val === null) continue;

    if      (code === "EXPORTS_USD")      d.total_exports_usd_b = val;
    else if (code === "IMPORTS_USD")      d.total_imports_usd_b = val;
    else if (code === "TRADE_BALANCE_USD") d.trade_balance_usd_b = val;
    else {
      const expM  = code.match(/^EXPORTS_TO_([A-Z]{2,3})$/);
      const impM  = code.match(/^IMPORTS_FROM_([A-Z]{2,3})$/);
      const depM  = code.match(/^TRADE_DEPENDENCY_([A-Z]{2,3})$/);
      if (expM) {
        const p = expM[1];
        d.by_partner[p] ??= _emptyPartnerRisk();
        d.by_partner[p].exports_usd_b = val;
      } else if (impM) {
        const p = impM[1];
        d.by_partner[p] ??= _emptyPartnerRisk();
        d.by_partner[p].imports_usd_b = val;
      } else if (depM) {
        const p = depM[1];
        d.by_partner[p] ??= _emptyPartnerRisk();
        d.by_partner[p].partner_share_pct = val;
        d.by_partner[p].partner_share     = val / 100;
        d.by_partner[p].dependency_risk   = _riskLevel(val);
      }
    }
  }

  // ── Pass 2: derive share percentages + top partners ────────────────────────
  for (const country of Object.keys(dep)) {
    for (const year of Object.keys(dep[country])) {
      const d = dep[country][year];
      const totalX = d.total_exports_usd_b;
      const totalM = d.total_imports_usd_b;
      const totalT = totalX + totalM;

      let maxExpPct = 0, maxImpPct = 0;

      for (const partner of Object.keys(d.by_partner)) {
        const bp  = d.by_partner[partner];
        const bil = bp.exports_usd_b + bp.imports_usd_b;
        bp.total_bilateral_usd_b = bil;

        if (totalT > 0) {
          bp.partner_share     = bil / totalT;
          bp.partner_share_pct = bp.partner_share * 100;
        }
        if (totalX > 0) {
          bp.export_share     = bp.exports_usd_b / totalX;
          bp.export_share_pct = bp.export_share * 100;
        }
        if (totalM > 0) {
          bp.import_share     = bp.imports_usd_b / totalM;
          bp.import_share_pct = bp.import_share * 100;
        }

        bp.dependency_risk = _riskLevel(bp.partner_share_pct);
        bp.export_risk     = _riskLevel(bp.export_share_pct);
        bp.import_risk     = _riskLevel(bp.import_share_pct);

        if (bp.export_share_pct > maxExpPct) {
          maxExpPct = bp.export_share_pct;
          d.top_export_partner   = partner;
          d.top_export_share_pct = bp.export_share_pct;
        }
        if (bp.import_share_pct > maxImpPct) {
          maxImpPct = bp.import_share_pct;
          d.top_import_partner   = partner;
          d.top_import_share_pct = bp.import_share_pct;
        }
      }
    }
  }

  return dep;
}

/** Normalise either JSON format into TfJson. Safe for static builds. */
function _normalize(raw: Record<string, unknown>): TfJson {
  if (!raw || typeof raw !== "object") {
    return { meta: _defaultMeta(raw), flows: [], dependency: {}, monthly: [], summary: [] };
  }

  // ── Format ①: already has the expected shape ──────────────────────────────
  if ("meta" in raw && "dependency" in raw) {
    return {
      meta:       (raw["meta"] ?? _defaultMeta(raw)) as TfMeta,
      flows:      (raw["flows"]   ?? []) as TfFlow[],
      dependency: (raw["dependency"] ?? {}) as Record<string, Record<string, TfYearDependency>>,
      monthly:    (raw["monthly"] ?? []) as TfFlow[],
      summary:    (raw["summary"] ?? []) as TfSummaryRow[],
    };
  }

  // ── Format ②: new pipeline flat-records format ────────────────────────────
  const records = (raw["records"] ?? []) as Array<Record<string, unknown>>;
  const years   = (raw["years"]   ?? [2024]) as number[];
  const dependency = _buildDependency(records);

  return {
    meta:       _defaultMeta(raw, years, dependency),
    flows:      [],
    dependency,
    monthly:    [],
    summary:    [],
  };
}

function _defaultMeta(
  raw: Record<string, unknown>,
  years?: number[],
  dep?: Record<string, Record<string, TfYearDependency>>,
): TfMeta {
  const resolvedYears = years
    ?? ((raw?.["years"]) as number[] | undefined)
    ?? [2024];

  const apiAvailable = Boolean(raw?.["comtrade_api_available"]);
  const reporterCount = dep
    ? Object.keys(dep).length
    : ((raw?.["reporters"] as unknown[]) ?? []).length || 11;

  return {
    generated_at:       (raw?.["fetched_at"] as string | undefined) ?? new Date().toISOString(),
    source:             (raw?.["source"]  as string | undefined)
                        ?? "UN Comtrade (public preview) + World Bank WDI",
    api_mode:           (raw?.["mode"]    as string | undefined) ?? "public_preview",
    reporters:          reporterCount,
    partners:           7,
    years:              resolvedYears,
    has_monthly:        false,
    data_status:        apiAvailable ? "live" : "placeholder",
    limitations: [
      "Bilateral partner flows use UN Comtrade public preview (500-record cap per request).",
      "India (IND) and EU bilateral flows may be missing — not available in public preview.",
      "Total exports/imports from World Bank WDI — ~1 year publication lag.",
      "Set COMTRADE_API_KEY in .env to enable authenticated Comtrade with full coverage.",
    ],
    dependency_formula: "partner_share = bilateral_trade / total_trade · ≥40% High · 20–40% Medium · <20% Low",
    refresh_note:       "Run: python scripts/fetch_un_comtrade.py --all-years",
  };
}

// ── Normalised data (safe for static build) ───────────────────────────────────

const _raw: TfJson = _normalize(_rawFile);


// ── Core exports ──────────────────────────────────────────────────────────────

export const TF_META:       TfMeta                                             = _raw.meta;
export const TF_FLOWS:      TfFlow[]                                           = _raw.flows       ?? [];
export const TF_DEPENDENCY: Record<string, Record<string, TfYearDependency>>   = _raw.dependency  ?? {};
export const TF_SUMMARY:    TfSummaryRow[]                                     = _raw.summary     ?? [];
export const TF_MONTHLY:    TfFlow[]                                           = _raw.monthly     ?? [];

export const TF_DATA_STATUS: "live" | "placeholder" =
  (_raw.meta?.data_status === "live") ? "live" : "placeholder";

export const TF_LATEST_YEAR: number =
  Math.max(...((_raw.meta?.years ?? [2024]).length > 0 ? (_raw.meta?.years ?? [2024]) : [2024]));


// ── Source metadata ───────────────────────────────────────────────────────────

export const TF_SOURCE_META: SourceMeta = {
  ...COMTRADE_SOURCE_BASE,
  fetched_at: _raw.meta?.generated_at ?? new Date().toISOString(),
};

export function getFlowSourceMeta(flow: TfFlow): SourceMeta {
  return {
    ...COMTRADE_SOURCE_BASE,
    fetched_at:  flow?.last_updated  ?? _raw.meta?.generated_at ?? new Date().toISOString(),
    source_url:  flow?.source_url    ?? COMTRADE_SOURCE_BASE.source_url,
    source:      flow?.source === "comtrade_wto_stats"
      ? "UN Comtrade / WTO Statistics"
      : (flow?.source ?? COMTRADE_SOURCE_BASE.source),
  };
}


// ── Reporter / Partner registry ───────────────────────────────────────────────

export interface TfCountry {
  code:  string;
  name:  string;
  flag:  string;
}

export const TF_REPORTERS: TfCountry[] = [
  { code: "THA", name: "Thailand",     flag: "🇹🇭" },
  { code: "VNM", name: "Vietnam",      flag: "🇻🇳" },
  { code: "MMR", name: "Myanmar",      flag: "🇲🇲" },
  { code: "KHM", name: "Cambodia",     flag: "🇰🇭" },
  { code: "LAO", name: "Laos",         flag: "🇱🇦" },
  { code: "MYS", name: "Malaysia",     flag: "🇲🇾" },
  { code: "SGP", name: "Singapore",    flag: "🇸🇬" },
  { code: "IDN", name: "Indonesia",    flag: "🇮🇩" },
  { code: "PHL", name: "Philippines",  flag: "🇵🇭" },
  { code: "BRN", name: "Brunei",       flag: "🇧🇳" },
  { code: "TLS", name: "Timor-Leste",  flag: "🇹🇱" },
];

export const TF_PARTNERS: TfCountry[] = [
  { code: "CHN", name: "China",          flag: "🇨🇳" },
  { code: "USA", name: "United States",  flag: "🇺🇸" },
  { code: "JPN", name: "Japan",          flag: "🇯🇵" },
  { code: "IND", name: "India",          flag: "🇮🇳" },
  { code: "KOR", name: "South Korea",    flag: "🇰🇷" },
  { code: "AUS", name: "Australia",      flag: "🇦🇺" },
  { code: "EUU", name: "European Union", flag: "🇪🇺" },
];

const _allCountries: TfCountry[] = [
  ...TF_REPORTERS,
  ...TF_PARTNERS,
  { code: "WLD", name: "World (Total)", flag: "🌐" },
];
export function getTfCountry(code: string): TfCountry | undefined {
  return _allCountries.find(c => c.code === code);
}


// ── Lookup helpers ────────────────────────────────────────────────────────────

/** Get dependency data for one reporter country in a given year. */
export function getCountryDependency(
  iso3: string,
  year: number = TF_LATEST_YEAR,
): TfYearDependency | null {
  return TF_DEPENDENCY[iso3]?.[String(year)] ?? null;
}

/** Get the risk profile for one bilateral pair. */
export function getPartnerRisk(
  reporterIso3: string,
  partnerIso3:  string,
  year:         number = TF_LATEST_YEAR,
): TfPartnerRisk | null {
  return TF_DEPENDENCY[reporterIso3]?.[String(year)]?.by_partner?.[partnerIso3] ?? null;
}

/** Get dependency risk level for one bilateral pair. */
export function getDependencyRisk(
  reporterIso3: string,
  partnerIso3:  string,
  year:         number = TF_LATEST_YEAR,
): DependencyRisk {
  return getPartnerRisk(reporterIso3, partnerIso3, year)?.dependency_risk ?? "low";
}

/** Get the full dependency risk matrix for all reporters × partners in a year. */
export function getAllDependencyRisks(
  year = TF_LATEST_YEAR,
): Record<string, Record<string, DependencyRisk>> {
  const result: Record<string, Record<string, DependencyRisk>> = {};
  for (const reporter of TF_REPORTERS) {
    result[reporter.code] = {};
    for (const partner of TF_PARTNERS) {
      result[reporter.code][partner.code] = getDependencyRisk(reporter.code, partner.code, year);
    }
  }
  return result;
}

/** Get the top trading partner for a reporter (by flow direction). */
export function getTopPartner(
  iso3:  string,
  flow:  "export" | "import" | "overall",
  year:  number = TF_LATEST_YEAR,
): { code: string; name: string; flag: string; share_pct: number } | null {
  const dep = getCountryDependency(iso3, year);
  if (!dep) return null;

  const code = flow === "import" ? (dep.top_import_partner ?? "") : (dep.top_export_partner ?? "");
  const share_pct = flow === "import"
    ? (dep.top_import_share_pct ?? 0)
    : (dep.top_export_share_pct ?? 0);

  if (!code) return null;
  const country = getTfCountry(code);
  return { code, name: country?.name ?? code, flag: country?.flag ?? "🌐", share_pct };
}

/** Get exports, imports, and trade balance for a country-year. */
export function getTradeBalance(
  iso3: string,
  year: number = TF_LATEST_YEAR,
): { exports: number; imports: number; balance: number } | null {
  const dep = getCountryDependency(iso3, year);
  if (!dep) return null;
  return {
    exports: dep.total_exports_usd_b ?? 0,
    imports: dep.total_imports_usd_b ?? 0,
    balance: dep.trade_balance_usd_b ?? 0,
  };
}

/** Get bilateral export/import data over years. */
export function getBilateralHistory(
  reporterIso3: string,
  partnerIso3:  string,
): Array<{ year: number; exports_usd_b: number; imports_usd_b: number; balance: number }> {
  const years = _raw.meta?.years ?? [TF_LATEST_YEAR];
  return years.map(yr => {
    const risk = getPartnerRisk(reporterIso3, partnerIso3, yr);
    return {
      year:          yr,
      exports_usd_b: risk?.exports_usd_b ?? 0,
      imports_usd_b: risk?.imports_usd_b ?? 0,
      balance:       (risk?.exports_usd_b ?? 0) - (risk?.imports_usd_b ?? 0),
    };
  });
}


// ── Precomputed matrix ────────────────────────────────────────────────────────

/** Full dependency risk matrix for latest year. */
export const DEPENDENCY_RISK_MATRIX = getAllDependencyRisks(TF_LATEST_YEAR);


// ── Display helpers ───────────────────────────────────────────────────────────

export const RISK_BADGE_STYLE: Record<DependencyRisk, { bg: string; text: string; label: string }> = {
  high:   { bg: "bg-red-100",     text: "text-red-700",     label: "High"   },
  medium: { bg: "bg-amber-100",   text: "text-amber-700",   label: "Medium" },
  low:    { bg: "bg-emerald-100", text: "text-emerald-700", label: "Low"    },
};

export const RISK_DOT_COLOR: Record<DependencyRisk, string> = {
  high:   "bg-red-500",
  medium: "bg-amber-400",
  low:    "bg-emerald-500",
};

export const RISK_CELL_BG: Record<DependencyRisk, string> = {
  high:   "bg-red-50 border-red-200",
  medium: "bg-amber-50 border-amber-200",
  low:    "bg-emerald-50 border-emerald-200",
};
