/**
 * frontend/data/worldbank-data.ts
 * ────────────────────────────────────────────────────────────────────────────
 * TypeScript adapter for the World Bank processed data.
 *
 * SOURCE FILE (generated by pipeline/fetch_worldbank.py):
 *   pipeline/data/processed/worldbank_indicators.json
 *
 * HOW TO REFRESH REAL DATA:
 *   cd pipeline
 *   python fetch_worldbank.py
 *   # then restart / rebuild the Next.js dev server
 *
 * EXPORTS
 * ───────
 *   WB_META              — metadata (generated_at, note, year_range, status)
 *   WB_INDICATORS        — indicator definitions {key → {wb_code, label, unit, …}}
 *   WB_RECORDS           — all flat records (1 per country-indicator-year)
 *   WB_DATA_STATUS       — "live" | "placeholder"
 *   ANNUAL_DATA_NOTE     — human-readable string for UI banners
 *
 *   getWbValue()         — single value lookup
 *   getWbHistory()       — full year-point array for one indicator
 *   getWbLatest()        — most recent non-missing value for one indicator
 *   getWbCountrySummary()— all latest values for one country
 *
 *   WB_COUNTRY_SUMMARIES — precomputed {iso3 → {indicatorKey → WbLatest}}
 *
 * INDICATORS IN THIS FILE (8 total)
 * ───────────────────────────────────
 *   gdpGrowth     NY.GDP.MKTP.KD.ZG   % YoY
 *   gdpNominal    NY.GDP.MKTP.CD       USD Billion
 *   inflation     FP.CPI.TOTL.ZG       % YoY
 *   unemployment  SL.UEM.TOTL.ZS       % of labor force
 *   fdiPctGdp     BX.KLT.DINV.WD.GD.ZS % of GDP
 *   exports       NE.EXP.GNFS.CD       USD Billion
 *   imports       NE.IMP.GNFS.CD       USD Billion
 *   population    SP.POP.TOTL          Millions
 *
 * IMPORTANT: World Bank data is ANNUAL only.
 * For quarterly series use national stats offices:
 *   Thailand → NESDC, Vietnam → GSO, Singapore → SingStat,
 *   Indonesia → BPS, Malaysia → DOSM.
 * ────────────────────────────────────────────────────────────────────────────
 */

// ── Raw JSON import ──────────────────────────────────────────────────────────
// eslint-disable-next-line @typescript-eslint/no-require-imports
const _raw = require("../../pipeline/data/processed/worldbank_indicators.json") as WbJson;


// ── Types ────────────────────────────────────────────────────────────────────

export type WbDataQuality = "available" | "estimated" | "old_data" | "missing";

export interface WbRecord {
  source_url:     string;
  last_updated:   string;
  country_code:   string;   // ISO3
  country_name:   string;
  indicator_code: string;   // WB code, e.g. "NY.GDP.MKTP.KD.ZG"
  indicator_key:  string;   // camelCase, e.g. "gdpGrowth"
  year:           number;
  value:          number | null;
  unit:           string;
  data_quality:   WbDataQuality;
}

export interface WbIndicatorMeta {
  wb_code:   string;
  label:     string;
  unit:      string;
  scale:     number;
  direction: "higher_is_better" | "higher_is_worse" | "lower_is_better" | "neutral";
  note:      string;
}

export interface WbMeta {
  generated_at:      string;
  source:            string;
  api_base:          string;
  annual_data_note:  string;
  year_range:        [number, number];
  countries_fetched: number;
  indicators_fetched: number;
  total_records:     number;
  real_data_points:  number;
  data_status:       string;
}

interface WbJson {
  meta:       WbMeta;
  indicators: Record<string, WbIndicatorMeta>;
  records:    WbRecord[];
}

/** A resolved "latest value" for one country-indicator pair */
export interface WbLatest {
  value:   number;
  year:    number;
  unit:    string;
  quality: WbDataQuality;
}

/** Year-value point (matches sample-data.ts YearPoint shape) */
export interface WbYearPoint {
  year:    number;
  value:   number;
  quality: WbDataQuality;
}


import { WB_SOURCE_BASE, type SourceMeta, type SourceConfidence } from "@/lib/source-meta";

// ── Core exports ─────────────────────────────────────────────────────────────

export const WB_META:        WbMeta                          = _raw.meta;
export const WB_INDICATORS:  Record<string, WbIndicatorMeta> = _raw.indicators;
export const WB_RECORDS:     WbRecord[]                      = _raw.records;

/** "live" once fetch_worldbank.py has been run; "placeholder" before that. */
export const WB_DATA_STATUS: "live" | "placeholder" =
  _raw.meta.data_status === "live" ? "live" : "placeholder";

/** Short note for UI banners */
export const ANNUAL_DATA_NOTE =
  "World Bank data is annual (not real-time or quarterly). " +
  "Data typically has a 1–2 year publication lag.";

/** Long note for detail panels */
export const ANNUAL_DATA_NOTE_FULL: string = _raw.meta.annual_data_note;

// ── Source metadata ───────────────────────────────────────────────────────────

/**
 * Global World Bank source metadata (applies to all WB indicator records).
 * Confidence is "high" for officially measured data; use getWbRecordSourceMeta()
 * to get a per-record SourceMeta that reflects the actual data_quality flag.
 */
export const WB_SOURCE_META: SourceMeta = {
  ...WB_SOURCE_BASE,
  fetched_at: _raw.meta.generated_at,
};

/**
 * Per-record source metadata — downgrades confidence for estimated / old data.
 * Pass to IndicatorCard's `source` prop for accurate quality signalling.
 */
export function getWbRecordSourceMeta(record: WbRecord): SourceMeta {
  const conf: SourceConfidence =
    record.data_quality === "available" ? "high"
    : record.data_quality === "estimated" ? "medium"
    : "low";

  return {
    ...WB_SOURCE_BASE,
    fetched_at:      record.last_updated ?? _raw.meta.generated_at,
    source_url:      record.source_url ?? WB_SOURCE_BASE.source_url,
    confidence:      conf,
    limitation_note:
      record.data_quality === "estimated"
        ? "This value is a World Bank estimate, not an official measured figure. " +
          "Treat with wider uncertainty margin."
        : record.data_quality === "old_data"
        ? "This indicator has not been updated recently. The value may be 3+ years old."
        : WB_SOURCE_BASE.limitation_note,
  };
}

/**
 * Get source metadata for a specific country-indicator, using the latest record.
 */
export function getWbIndicatorSourceMeta(iso3: string, indicatorKey: string): SourceMeta {
  const rec = WB_RECORDS
    .filter(r => r.country_code === iso3 && r.indicator_key === indicatorKey && r.value !== null)
    .sort((a, b) => b.year - a.year)[0];

  if (!rec) return WB_SOURCE_META;
  return getWbRecordSourceMeta(rec);
}


// ── Lookup helpers ────────────────────────────────────────────────────────────

/**
 * Get a single value for a country-indicator-year.
 * Returns null if the cell is missing or the record doesn't exist.
 */
export function getWbValue(
  iso3:         string,
  indicatorKey: string,
  year:         number,
): number | null {
  const rec = WB_RECORDS.find(
    r => r.country_code === iso3 && r.indicator_key === indicatorKey && r.year === year,
  );
  return rec?.value ?? null;
}

/**
 * Get the data quality flag for a country-indicator-year.
 */
export function getWbQuality(
  iso3:         string,
  indicatorKey: string,
  year:         number,
): WbDataQuality | null {
  const rec = WB_RECORDS.find(
    r => r.country_code === iso3 && r.indicator_key === indicatorKey && r.year === year,
  );
  return rec?.data_quality ?? null;
}

/**
 * Get the full year-by-year history for one country-indicator pair.
 * Only returns years where value is non-null.
 * Sorted ascending by year.
 */
export function getWbHistory(
  iso3:         string,
  indicatorKey: string,
): WbYearPoint[] {
  return WB_RECORDS
    .filter(r =>
      r.country_code  === iso3 &&
      r.indicator_key === indicatorKey &&
      r.value !== null,
    )
    .map(r => ({
      year:    r.year,
      value:   r.value as number,
      quality: r.data_quality,
    }))
    .sort((a, b) => a.year - b.year);
}

/**
 * Get the most recent non-missing value for a country-indicator.
 * Prefers real data ("available") over estimated. Returns null if no data.
 */
export function getWbLatest(
  iso3:         string,
  indicatorKey: string,
): WbLatest | null {
  const recs = WB_RECORDS
    .filter(r =>
      r.country_code  === iso3 &&
      r.indicator_key === indicatorKey &&
      r.value !== null,
    )
    .sort((a, b) => b.year - a.year);  // newest first

  // Prefer real (non-estimated) data
  const realRec = recs.find(r => r.data_quality !== "estimated");
  const best = realRec ?? recs[0];

  if (!best) return null;
  return {
    value:   best.value as number,
    year:    best.year,
    unit:    best.unit,
    quality: best.data_quality,
  };
}

/**
 * Get all latest values for one country — all 8 indicators.
 * Returns a dict: { indicatorKey → WbLatest | null }
 */
export function getWbCountrySummary(
  iso3: string,
): Record<string, WbLatest | null> {
  return Object.fromEntries(
    Object.keys(WB_INDICATORS).map(key => [key, getWbLatest(iso3, key)]),
  );
}


// ── Precomputed country summaries ─────────────────────────────────────────────

/**
 * All country summaries, precomputed at module load time.
 * WB_COUNTRY_SUMMARIES[iso3][indicatorKey] → WbLatest | null
 *
 * Note: only countries actually present in the data will have entries.
 * Countries with no records at all (e.g. EU bloc) will be missing from this map.
 */
const _countrySet = new Set(WB_RECORDS.map(r => r.country_code));

export const WB_COUNTRY_SUMMARIES: Record<string, Record<string, WbLatest | null>> =
  Object.fromEntries(
    [..._countrySet].map(iso3 => [iso3, getWbCountrySummary(iso3)]),
  );


// ── Quality badge helpers ──────────────────────────────────────────────────────

export const QUALITY_LABEL: Record<WbDataQuality, string> = {
  available:  "Live",
  estimated:  "Estimated",
  old_data:   "Old data",
  missing:    "No data",
};

export const QUALITY_COLOR: Record<WbDataQuality, string> = {
  available:  "bg-emerald-100 text-emerald-700",
  estimated:  "bg-amber-100   text-amber-700",
  old_data:   "bg-slate-100   text-slate-600",
  missing:    "bg-red-100     text-red-600",
};

export const QUALITY_DOT: Record<WbDataQuality, string> = {
  available:  "bg-emerald-500",
  estimated:  "bg-amber-400",
  old_data:   "bg-slate-400",
  missing:    "bg-red-400",
};


// ── Indicator display helpers ──────────────────────────────────────────────────

/** Human-readable label for each indicator key */
export const WB_INDICATOR_LABELS: Record<string, string> = Object.fromEntries(
  Object.entries(WB_INDICATORS).map(([k, v]) => [k, v.label]),
);

/** Unit for each indicator key */
export const WB_INDICATOR_UNITS: Record<string, string> = Object.fromEntries(
  Object.entries(WB_INDICATORS).map(([k, v]) => [k, v.unit]),
);

/** Ordered list of indicator keys for display */
export const WB_INDICATOR_KEYS = [
  "gdpGrowth",
  "gdpNominal",
  "inflation",
  "unemployment",
  "fdiPctGdp",
  "exports",
  "imports",
  "population",
] as const;

export type WbIndicatorKey = typeof WB_INDICATOR_KEYS[number];
